ENH: Update noxfile and env
gabalafou/accessibility pull request #2
Opened 2022-02-10 16:39 UTC by trallard

This PR adds the following

- Enhancements to noxfile to use conda and streamline installs
- Uses environment.yaml instead of requirements.txt
- Small docs

2022-02-10 16:51 UTC, gabalafou requested changes

2022-02-10 16:51 UTC, gabalafou commented on tests/retrolab/environment.yml
> +    - git+https://github.com/jupyterlab/retrolab.git@v0.3.19#egg=retrolab
this is what I was looking for! :)

2022-02-10 16:51 UTC, gabalafou commented on tests/retrolab/README.md
> +2. Run the test with snox from the command line:
```suggestion
2. Run the test with nox from the command line:
```

now you've got me wondering what a snox would be if a snox were a thing... sounds like something from Dr. Seuss or Roald Dahl might come up with...

2022-02-10 16:51 UTC, gabalafou commented on tests/retrolab/README.md
> +- python > 3.7
mamba?

```suggestion
- mamba
- python > 3.7
```

2022-02-10 16:51 UTC, gabalafou commented on tests/retrolab/noxfile.py
> +requirements = dependencies.pop(-1).get("pip")
oh... you cheated :-P

2022-02-10 16:51 UTC, gabalafou commented on tests/retrolab/noxfile.py
> +    This is faster than recreating, updating or pruning the environment using
oh why is that? (faster)

2022-02-10 16:51 UTC, gabalafou commented on tests/retrolab/noxfile.py
> +    conda env create -f we install depency into the session venv.
```suggestion
    conda env create -f we install dependency into the session venv.
```

2022-02-10 16:51 UTC, gabalafou commented on tests/retrolab/README.md
> +    nox -s a11y_tests
but if they don't have mamba, this will fail won't it?

2022-02-10 16:54 UTC, trallard commented on tests/retrolab/README.md
> +2. Run the test with snox from the command line:
😆  just a typo but would be a nice name for another tool to add to the tox/nox confusion

2022-02-10 16:54 UTC, trallard commented on tests/retrolab/README.md
> +- python > 3.7
of course 😮‍💨

2022-02-10 16:55 UTC, trallard commented on tests/retrolab/noxfile.py
> +requirements = dependencies.pop(-1).get("pip")
yes - can talk about why - but long story short nox does not play as nicely with conda as it does with venv

2022-02-10 16:56 UTC, trallard commented on tests/retrolab/README.md
> +    nox -s a11y_tests
yup - maybe can add a check for mamba or conda and allow for the system to set the default 🤔  actually will do that

2022-02-10 16:56 UTC, trallard commented on tests/retrolab/noxfile.py
> +    This is faster than recreating, updating or pruning the environment using
part of the same story as above

2022-02-10 17:15 UTC, gabalafou commented on tests/retrolab/README.md
> +    nox -s a11y_tests
great! will be on the lookout for your update

2022-05-06 20:13 UTC, gabalafou commented
Thanks @trallard! That Dockerfile looks like it was a lot of work. I'm going to merge this is because I want to build on top of it 🚀

2022-05-06 20:24 UTC, merged